name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - run: docker run -v $(pwd):/source opendxl/opendxl-ontology-dev /source/dist.sh
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist    
