name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
      
    - name: Build and validate
      run: docker run -v $(pwd):/source christsmith/ontology-dev /source/dist.sh
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist    

